charte_info:
  class: sfDoctrineRouteCollection
  options:
    model:                CharteInfo
    module:               charte_info
    prefix_path:          /charte_info
    column:               id
    with_wildcard_routes: true

semestre:
  class: sfDoctrineRouteCollection
  options:
    model:                Semestre
    module:               semestre
    prefix_path:          /semestre
    column:               id
    with_wildcard_routes: true

role:
  class: sfDoctrineRouteCollection
  options:
    model:                Role
    module:               role
    prefix_path:          /role
    column:               id
    with_wildcard_routes: true

asso_member:
  class: sfDoctrineRouteCollection
  options:
    model:                AssoMember
    module:               asso_member
    prefix_path:          /asso_member
    column:               id
    with_wildcard_routes: true

asso:
  class: sfDoctrineRouteCollection
  options:
    model:                Asso
    module:               asso
    prefix_path:          /asso
    column:               id
    with_wildcard_routes: true

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
