generator:
  class: sfDoctrineGenerator
  param:
    model_class:           InfoJobSignalement
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          info_job_signalement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Offres signal√©es
        display: [type_id, commentaire, _lien]
        actions: {}
        batch_actions: {}
        object_actions: {}
      filter:
        class: false
      form: ~
      edit: ~
      new: ~
