# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

cas:
  url: /cas
  param: { module: utcCas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: utcCas, action: logout }

#Asso
assos_list:
  url:   /asso
  param: { module: asso, action: index }

assos_list_pole:
  url:   /asso/pole/:pole
  param: { module: asso, action: index }

assos_show:
  url:   /asso/:login
  class: sfDoctrineRoute
  param: { module: asso, action: show }
  options: { model: Asso, type: object, method_for_query: retrieveAsso }

asso_articles:
  url:   /asso/articles/:login
  class: sfDoctrineRoute
  param: { module: asso, action: articles }
  options: { model: Asso, type: object }

asso_events:
  url:   /asso/events/:login
  class: sfDoctrineRoute
  param: { module: asso, action: events }
  options: { model: Asso, type: object }

asso_bureau:
  url:   /asso/bureau/:login
  class: sfDoctrineRoute
  param: { module: asso, action: bureau }
  options: { model: Asso, type: object }

asso_trombi:
  url:   /asso/trombi/:login
  class: sfDoctrineRoute
  param: { module: asso, action: trombinoscope }
  options: { model: Asso, type: object }

asso_member:
  url:   /asso/membres/:login
  class: sfDoctrineRoute
  param: { module: asso, action: member }
  options: { model: Asso, type: object }

member_edit:
  url:   /asso/membres/:asso/edit/:id
  class: sfDoctrineRoute
  param: { module: member, action: edit }
  options: { model: AssoMember, type: object }
member_update:
  url:  /asso/membres/:asso/update/:id
  param: { module: member, action: update }
member_delete:
  url:  /asso/membres/:asso/delete/:id
  param: { module: member, action: delete }

asso_search:
  url:   /asso/search
  param: { module: asso, action: search }

asso_search_json:
  url:   /asso/search.json
  param: { module: asso, action: search, sf_format: json }

asso_charte_post:
  url: /asso/charte
  param: {module: asso, action: chartePost }

asso_edit:
  url: /asso/:login/edit
  class: sfDoctrineRoute
  param: { module: asso, action: edit }
  options: { model: Asso, type: object }

asso_join:
  url: /asso/:login/join
  class: sfDoctrineRoute
  param: { module: asso, action: join }
  options: { model: Asso, type: object }

asso_leave:
  url: /asso/:login/leave
  class: sfDoctrineRoute
  param: { module: asso, action: leave }
  options: { model: Asso, type: object }

asso_follow:
  url: /asso/:login/follow
  class: sfDoctrineRoute
  param: { module: asso, action: follow }
  options: { model: Asso, type: object }

asso_unfollow:
  url: /asso/:login/unfollow
  class: sfDoctrineRoute
  param: { module: asso, action: unfollow }
  options: { model: Asso, type: object }

asso_update:
  url: /asso/:id/update
  param: { module: asso, action: update }

asso_charte:
  url: /asso/:login/charte
  class: sfDoctrineRoute
  param: { module: asso, action: charte }
  options: { model: Asso, type: object }

asso_charte_confirm:
  url: /asso/:id/charte/confirm
  class: sfDoctrineRoute
  param: { module: asso, action: charteConfirm }
  options: { model: CharteInfo, type: object }

asso_charte_refuse:
  url: /asso/:id/charte/refuse
  class: sfDoctrineRoute
  param: { module: asso, action: charteRefuse }
  options: { model: CharteInfo, type: object }

#Articles
articles_list:
  url:   /article
  param: { module: article, action: index }

articles_list_asso:
  url:   /article/asso/:login
  class: sfDoctrineRoute
  param: { module: article, action: list }
  options: { model: Asso, type: object }

article_show:
  url:   /article/show/:id
  class: sfDoctrineRoute
  param: { module: article, action: show }
  options: { model: Article, type: object }

article_edit:
  url:  /article/edit/:id
  class: sfDoctrineRoute
  param: { module: article, action: edit }
  options: { model: Article, type: object }

article_update:
  url:  /article/update/:id
  param: { module: article, action: update }

article_delete:
  url:  /article/delete/:id
  param: { module: article, action: delete }
article_create:
  url: /article/create
  param: { module: article, action: create }

article_new:
  url: /article/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: article, action: new }

#GaleriePhoto
galerie_photo_list:
  url:   /galerie
  param: {module: galerie, action: index}

galerie_photo_show_fullscreen:
  url:   /galerie/show/:id/photo/:photo/pass/:pass
  class: sfDoctrineRoute
  param: { module: galerie, action: show }
  options: { model: GaleriePhoto, type: object }

galerie_photo_show_fullscreen_nopass:
  url:   /galerie/show/:id/photo/:photo
  class: sfDoctrineRoute
  param: { module: galerie, action: show }
  options: { model: GaleriePhoto, type: object }

galerie_photo_show:
  url:   /galerie/show/:id
  class: sfDoctrineRoute
  param: { module: galerie, action: show }
  options: { model: GaleriePhoto, type: object }

galerie_photo_edit:
  url:  /galerie/edit/:id
  class: sfDoctrineRoute
  param: { module: galerie, action: edit }
  options: { model: GaleriePhoto, type: object }

galerie_photo_update:
  url:  /galerie/update/:id
  param: { module: galerie, action: update }

galerie_photo_delete:
  url:  /galerie/delete/:id
  param: { module: galerie, action: delete }

galerie_photo_create:
  url: /galerie/create
  param: { module: galerie, action: create }

galerie_photo_new:
  url: /galerie/new/:id
  class: sfDoctrineRoute
  options: { model: Event, type: object }
  param: { module: galerie, action: new }

#Photo
photo_edit:
  url:  /photo/edit/:id
  class: sfDoctrineRoute
  param: { module: photo, action: edit }
  options: { model: Photo, type: object }

photo_update:
  url:  /photo/update/:id
  param: { module: photo, action: update }

photo_delete:
  url:  /photo/delete/:id
  param: { module: photo, action: delete }

photo_create:
  url: /photo/create
  param: { module: photo, action: create }

photo_create_format:
  url: /photo/create.:sf_format
  param: { module: photo, action: create }
  requirements:
    sf_format: (?:html|json)

photo_new:
  url: /photo/new/:id
  class: sfDoctrineRoute
  options: { model: GaleriePhoto, type: object }
  param: { module: photo, action: new }

#Uv
uv_list:
  url:   /uv
  param: { module: uv, action: index }

uv_update:
  url:  /uv/update/:id
  param: { module: uv, action: update }

uv_delete:
  url:  /uv/delete/:id
  param: { module: uv, action: delete }

uv_create:
  url: /uv/create
  param: { module: uv, action: create }

uv_new:
  url: /uv/new
  param: { module: uv, action: new }

uv_edit:
  url:  /uv/edit/:id
  class: sfDoctrineRoute
  param: { module: uv, action: edit }
  options: { model: Uv, type: object }

#Sport
sport_list:
  url:   /sport
  param: { module: sport, action: index }

sport_update:
  url:  /sport/update/:id
  param: { module: sport, action: update }

sport_delete:
  url:  /sport/delete/:id
  param: { module: sport, action: delete }

sport_create:
  url: /sport/create
  param: { module: sport, action: create }

sport_new:
  url: /sport/new
  param: { module: sport, action: new }

sport_edit:
  url:  /sport/edit/:id
  class: sfDoctrineRoute
  param: { module: sport, action: edit }
  options: { model: Sport, type: object }

#Profile
profile_show:
  url:   /profile/:username
  class: sfDoctrineRoute
  options: {model: sfGuardUser, type: object}
  param: { module: profile, action: show }


profile_identite_edit:
  url:  /profile/identite/edit/:id
  class: sfDoctrineRoute
  options: { model: Profile, type: object }
  param: { module: profile, action: editIdentite }

profile_identite_update:
  url:  /profile/identite/update/:id
  param: { module: profile, action: updateIdentite }

profile_infoPerso_edit:
  url:  /profile/infoPerso/edit/:id
  class: sfDoctrineRoute
  options: { model: Profile, type: object }
  param: { module: profile, action: editInfoPerso }

profile_infoPerso_update:
  url:  /profile/infoPerso/update/:id
  param: { module: profile, action: updateInfoPerso }

profile_infoSupp_edit:
  url:  /profile/infoSupp/edit/:id
  class: sfDoctrineRoute
  options: { model: Profile, type: object }
  param: { module: profile, action: editInfoSupp }

profile_infoSupp_update:
  url:  /profile/infoSupp/update/:id
  param: { module: profile, action: updateInfoSupp }

profile_infoSupp_add:
  url: /profile/add
  param: { module: sport, action: add }

#Events
events_list:
  url: /event.:sf_format
  param: { module: event, action: index }
  requirements:
    sf_format: (?:html|json)

events_list_asso:
  url:   /event/asso/:id
  class: sfDoctrineRoute
  param: { module: event, action: list }
  options: { model: Asso, type: object }

event_show:
  url: /event/show/:id
  class: sfDoctrineRoute
  param: { module: event, action: show }
  options: { model: Event, type: object }

event_edit:
  url: /event/edit/:id
  class: sfDoctrineRoute
  param: { module: event, action: edit }
  options: { model: Event, type: object }

event_update:
  url:  /event/update/:id
  param: { module: event, action: update }

event_delete:
  url:  /event/delete/:id
  param: { module: event, action: delete }
event_create:
  url: /event/create
  param: { module: event, action: create }
event_new:
  url: /event/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: event, action: new }

event_update:
  url:  /event/update/:id
  param: { module: event, action: update }

event_delete:
  url:  /event/delete/:id
  param: { module: event, action: delete }

event_register:
  url: /event/register/:id
  param: { module: event, action: register }

event_unregister:
  url: /event/unregister/:id
  param: { module: event, action: unregister }

event_create:
  url: /event/create
  param: { module: event, action: create }
event_new:
  url: /event/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: event, action: new }


agenda_detail:
  url:   /event/calendar
  param: { module: event, action: calendar }

#Materiel
materiel:
  url:   /materiel/asso/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: materiel, action: index }

materiel_show:
  url:   /materiel/show/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: show }
  options: { model: Materiel, type: object }

materiel_edit:
  url:  /materiel/edit/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: edit }
  options: { model: Materiel, type: object }

materiel_update:
  url:  /materiel/update/:id
  param: { module: materiel, action: update }

materiel_delete:
  url:  /materiel/delete/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: delete }
  options: { model: Materiel, type: object }

materiel_create:
  url: /materiel/create
  param: { module: materiel, action: create }

materiel_new:
  url: /materiel/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: materiel, action: new }

materiel_ajout:
  url: /materiel/ajout/:id
  class: sfDoctrineRoute
  options: { model: Materiel, type: object }
  param: { module: materiel, action: ajout }

materiel_update_ajout:
  url:  /materiel/ajout/update/:id
  param: { module: materiel, action: updateAjout }

materiel_create_ajout:
  url: /materiel/ajout/create
  param: { module: materiel, action: createAjout }

#Emprunt
emprunt_delete:
  url:  /emprunt/delete/:id
  param: { module: emprunt, action: delete }

emprunt_create:
  url: /emprunt/create
  param: { module: emprunt, action: create }

emprunt_new:
  url: /emprunt/:id/new
  class: sfDoctrineRoute
  options: { model: Materiel, type: object }
  param: { module: emprunt, action: new }

emprunt_rendre:
  url: /emprunt/rendre/:id
  class: sfDoctrineRoute
  options: { model: Emprunt, type: object }
  param: { module: emprunt, action: rendre }

#Annonce
#annonce:
#  url:   /annonce
#  param: { module: annonce, action: index }

#annonce_show:
#  url:   /annonce/show/:id
#  class: sfDoctrineRoute
#  param: { module: annonce, action: show }
#  options: { model: Materiel, type: object }

#annonce_edit:
#  url:  /annonce/edit/:id
#  class: sfDoctrineRoute
#  param: { module: annonce, action: edit }
#  options: { model: Materiel, type: object }

#annonce_update:
#  url:  /annonce/update/:id
#  param: { module: annonce, action: update }

#annonce_delete:
#  url:  /annonce/delete/:id
#  class: sfDoctrineRoute
#  param: { module: annonce, action: delete }
#  options: { model: Materiel, type: object }

#annonce_create:
#  url: /annonce/create
#  param: { module: annonce, action: create }

#annonce_new:
#  url: /annonce/new
#  param: { module: annonce, action: new }
  
#InfoJob
infojob_home:
    url: /infojob
    param: { module: infojob, action: offres }

infojob_offre_home:
    url: /infojob/offres
    param: { module: infojob, action: offres }
    
infojob_monprofil:
    url: /infojob/monprofil
    param: { module: infojob, action: monprofil }
    
infojob_offre_show:
  url:   /infojob/show/:id
  param: { module: infojob, action: show }

infojob_offre_new:
  url:  /infojob/new
  param: { module: infojob, action: new }

infojob_offre_create:
  url:  /infojob/create
  param: { module: infojob, action: create }

infojob_offre_edit:
  url:  /infojob/edit/:key
  param: { module: infojob, action: edit }

infojob_offre_update:
  url:  /infojob/update/:key
  param: { module: infojob, action: update }

infojob_offre_delete:
  url:  /infojob/delete/:key
  param: { module: infojob, action: delete }

infojob_offre_activate:
  url: /infojob/activate/:key
  param: { module: infojob, action: activate }

infojob_offre_myoffer:
  url: /infojob/myoffer/:id
  param: { module: infojob, action: myoffer }

infojob_offre_myofferdo:
  url: /infojob/myoffer
  param: { module: infojob, action: myofferdo }

infojob_offre_signal:
  url: /infojob/signal/:id
  class: sfDoctrineRoute
  param: { module: infojob, action: signal }
  options: { model: InfoJobOffre, type: object }

infojob_offre_signaldo:
  url: /infojob/signaldo
  param: { module: infojob, action: signaldo }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_register:
  url: /inscription
  param: { module: sfGuardRegister, action: index }

register_activation:
  url: /inscription/activation/:activation_key
  class: sfDoctrineRoute
  param: { module: sfGuardRegister, action: activation }
  options: { model: Activation, type: object }

register_resend:
  url: /inscription/activation
  param: { module: sfGuardRegister, action: resend }

abonnement_list:
  url: /abonnement/:show
  param: { module: abonnement, action: show}

services:
  url: /services
  param: {module: services, action: index}

services_follow:
  url: /services/:nom/follow
  class: sfDoctrineRoute
  param: { module: services, action: follow }
  options: { model: Service, type: object }

services_unfollow:
  url: /services/:nom/unfollow
  class: sfDoctrineRoute
  param: { module: services, action: unfollow }
  options: { model: Service, type: object }

partenaires:
  url: /partenaires
  param: {module: partenaires, action: index}

gesmail_create:
  url: /asso/:login/gesmail/create
  param: { module: gesmail, action: create }

gesmail_docreate:
  url: /asso/:login/gesmail/docreate
  param: { module: gesmail, action: docreate }

gesmail_delete:
  url: /asso/:login/gesmail/dodelete/:id
  param: { module: gesmail, action: dodelete }

gesmail_box_delete:
  url: /asso/:login/gesmail/delete/:box
  param: { module: gesmail, action: delete }

gesmail_box_add:
  url: /asso/:login/gesmail/add/:box
  param: { module: gesmail, action: add }

gesmail_box:
  url: /asso/:login/gesmail/:box
  class: sfDoctrineRoute
  param: { module: gesmail, action: index }
  options: { model: Asso, type: object }

gesmail:
  url: /asso/:login/gesmail
  class: sfDoctrineRoute
  param: { module: gesmail, action: index }
  options: { model: Asso, type: object }

weekmail:
  url: /weekmail
  param: { module: weekmail, action: index }

#Locaux
locaux_charte:
  url: /asso/:login/locaux
  class: sfDoctrineRoute
  param: { module: locaux, action: charte }
  options: { model: Asso, type: object } 

locaux_create:
  url: /locaux/create
  param: { module: locaux, action: create }

locaux_ctrl:
  url: /locaux/:id
  class: sfDoctrineRoute
  param: { module: locaux, action: locauxCtrl }
  options: { model: CharteLocaux, type: object }

locaux_post:
  url: /locaux/post
  param: { module: locaux, action: locauxPost }

locaux_accept:
  url: /locaux/:id/accept
  class: sfDoctrineRoute
  param: { module: locaux, action: locauxAccept }
  options: { model: CharteLocaux, type: object }

locaux_refuse:
  url: /locaux/:id/refuse
  class: sfDoctrineRoute
  param: { module: locaux, action: locauxRefuse }
  options: { model: CharteLocaux, type: object }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#default_json:
#  url:   /json/:module/:action/*
#  param: { sf_format: json }
#default:
#  url:   /:module/:action/*
