# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [jquery-ui-1.8.12.custom.css, main.css]

  javascripts:    [jquery-1.5.1.min.js, jquery-ui-1.8.12.custom.min.js]

  has_layout:     true
  layout:         layout
