generator:
  class: sfDoctrineGenerator
  param:
    model_class:           InfoJobOffre
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          info_job_offre
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {label: Modifier}
      fields:
        expiration_date: {label: Expiration}
        archivage_date: {label: Archiv√©e ?}
      list:
        title: Offres
        display: [titre, email, expiration_date, archivage_date, _lien]
        actions: {}
        batch_actions:
          archiver: ~
        object_actions:
          _edit: ~
          archiver: ~
        sort: [created_at, desc]
      filter:
        display: [titre, texte, lieu, email, created_at, archivage_date]
      form: ~
      edit:
        title: Modifier une offre
      new: ~
