charte_locaux:
  class: sfDoctrineRouteCollection
  options:
    model:                CharteLocaux
    module:               charte_locaux
    prefix_path:          /charte_locaux
    column:               id
    with_wildcard_routes: true

infojob:
  url: /infojob
  param: { module: infojob, action: index }

info_job_signalement:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobSignalement
    module:               infojob_signalement
    prefix_path:          /infojob_signalement
    column:               id
    with_wildcard_routes: true


info_job_offre:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobOffre
    module:               infojob_offre
    prefix_path:          /infojob/offre
    column:               id
    with_wildcard_routes: true

info_job_disponibilite:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobDisponibilite
    module:               infojob_disponibilite
    prefix_path:          /infojob/disponibilite
    column:               id
    with_wildcard_routes: true

info_job_categorie:
  class: sfDoctrineRouteCollection
  options:
    model:                InfoJobCategorie
    module:               infojob_categorie
    prefix_path:          /infojob/categorie
    column:               id
    with_wildcard_routes: true

service:
  class: sfDoctrineRouteCollection
  options:
    model:                Service
    module:               service
    prefix_path:          /service

weekmail:
  url: /weekmail
  param: { module: weekmail, action: index }
weekmail_show:
  url:   /article/show/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: show }
  options: { model: Weekmail, type: object }
weekmail_edit:
  url:  /article/edit/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: edit }
  options: { model: Weekmail, type: object }
weekmail_update:
  url:  /weekmail/update/:id
  param: { module: weekmail, action: update }
weekmail_delete:
  url:  /weekmail/delete/:id
  param: { module: weekmail, action: delete }
weekmail_create:
  url: /weekmail/create
  param: { module: weekmail, action: create }
weekmail_new:
  url: /weekmail/new
  param: { module: weekmail, action: new }
weekmail_publish:
  url: /weekmail/publish/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: publish }
  options: { model: Weekmail, type: object }
weekmail_refuse:
  url: /weekmail/refuse/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: refuse }
  options: { model: Article, type: object }
weekmail_accept:
  url: /weekmail/accept/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: accept }
  options: { model: Article, type: object }
weekmail_delete_article:
  url:  /weekmail/delete_article/:id
  class: sfDoctrineRoute
  param: { module: weekmail, action: deleteArticle }
  options: { model: WeekmailArticle, type: object }

charte_info:
  class: sfDoctrineRouteCollection
  options:
    model:                CharteInfo
    module:               charte_info
    prefix_path:          /chartes
    column:               id
    with_wildcard_routes: true

cotisants:
  url: /cotisants
  param: { module: cotisants, action: index }

cotisants_edit:
  url: /cotisants/edit
  param: { module: cotisants, action: edit }
  
cotisants_cotisation:
  url: /cotisants/cotisation
  param: { module: cotisants, action: cotisation }

cas:
  url: /cas
  param: { module: utcCas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: utcCas, action: logout }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }
