# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        BDE Admin
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css,admin.css]

  javascripts:    [jquery-1.7.2.min.js, bootstrap.min.js]

  has_layout:     true
  layout:         layout
